name: studio_foto
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.1.6
  carousel_slider: ^4.1.1
  ticket_widget: ^0.0.1
  empty_widget: ^0.0.5
  ticket_material: ^0.3.1
  flutter_native_splash: ^2.2.16
  salomon_bottom_bar: ^3.3.1
  animated_widgets: ^1.1.0
  google_fonts: ^3.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/paket/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/montserrat/Montserrat.ttf
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
